Refactor storage setup scripts and update service condition check

diff --git a/files/system/usr/libexec/dank-bluebuild/post-login-setup/script.d/bashrc-fastfetch b/files/system/usr/libexec/dank-bluebuild/post-login-setup/script.d/bashrc-fastfetch
--- a/files/system/usr/libexec/dank-bluebuild/post-login-setup/script.d/bashrc-fastfetch
+++ b/files/system/usr/libexec/dank-bluebuild/post-login-setup/script.d/bashrc-fastfetch
@@ -17,7 +17,7 @@ failed() {
     exit 1
 }
 
-echo "fastfetch" >> ~/.bashrc || failed
+echo "fastfetch" >> "$HOME"/.bashrc || failed
 
 echo "Successfully added Fastfetch to '~/.bashrc'."
 exit 0
